### ISSUE TITLE
Cannot ignore structs

### ISSUE THREAD

**Issue by tomsisk** [gocarina/gocsv#107]
#94 created a bug where you can no longer ignore structs when marshalling

```go
type Quote struct {
	Symbol 	string
	Sector 	sql.NullString 	 `csv:"-"` // should be ignored
}
```

from sql package:
```go
type NullString struct {
        String string
        Valid  bool // Valid is true if String is not NULL
}
```

Will always give you:
```csv
AAPL,-SEC,true
GOOGL,,false
```

**Comment by casank25** [comment]
Having same issue... did you find any work around?

**Comment by tomsisk** [comment]
I fell back to the commit before it, which obviously isn't ideal, but worked for my needs: 3ae681a0d071f6a8460873ed6885a70b9b6b12a5

**Comment by qhenkart** [comment]
The issue and mistake in the code is accurately explained here https://github.com/golang/go/issues/4514
