### ISSUE TITLE
No suitable API for millons of records.

### ISSUE THREAD

**Issue by leeychee** [gocarina/gocsv#14]
Sometimes, we need to generate millions of records for test.
`func Marshal(in interface{}, out io.Writer) (err error) `need to generate records first, which spends lots of memory.

Can we support API like `func Marshal(c <-chan interface{}, out io.Writer) (err error)`?

**Comment by joeblew99** [comment]
+1 i also have a similar need. Have a ton of CSV data to parse and anything to reduce memory and GC is a help. 

Using a CHannel will allow it to be multithreaded ?

**Comment by pikanezi** [comment]
I added a MarshalChan. Here is the [test](https://github.com/gocarina/gocsv/blob/master/encode_test.go#L107).

Does it meet your needs?

**Comment by JonathanPicques** [comment]
Does it also need to read from a chan?

**Comment by leeychee** [comment]
LGTM

**Comment by pikanezi** [comment]
Feel free to open it again if you feel like it does not meet your needs.
