### ISSUE TITLE
UnmarshalBytes not marshalling data from first column

### ISSUE THREAD

**Issue by marcsantiago** [gocarina/gocsv#158]
I'm trying to unmarshal CSV data into a struct. I noticed data was missing from the structs. Tags are well formed and == the headers on the csv. 
Data from the first column is missing in every case, I can switch around the columns in the CSV and watch the data be missing from the Go struct in real time.

Go1.14 incase its version related.

**Comment by marcsantiago** [comment]
This has been addressed in closed issues, the BOM encoding from excel was the cause.

**Comment by bohehe** [comment]
So, how did you solve this problem? thanks in advance

**Comment by marcsantiago** [comment]
@bohehe when working with excel when you save and or export as csv, often times the file gets saved with the BOM encoding. The solution is to simply open the csv with a text editor. I use sublime and ensure the encoding is simply UFT 8.

<img width="695" alt="Screen Shot 2020-07-13 at 1 27 20 PM" src="https://user-images.githubusercontent.com/7970268/87334495-be3a6980-c50c-11ea-815e-74d8f1f123ff.png">

**Comment by bohehe** [comment]
> @bohehe when working with excel when you save and or export as csv, often times the file gets saved with the BOM encoding. The solution is to simply open the csv with a text editor. I use sublime and ensure the encoding is simply UFT 8.
> 
> <img alt="Screen Shot 2020-07-13 at 1 27 20 PM" width="695" src="https://user-images.githubusercontent.com/7970268/87334495-be3a6980-c50c-11ea-815e-74d8f1f123ff.png">

Thanks for your kind advice. I have solved this by 
1. convert the original bytes with BOM into new bytes without BOM using [this repo](https://github.com/dimchansky/utfbom)
2. read from new bytes using gocsv.UnmarshalBytes()

`
bodyWithoutBom, err := ioutil.ReadAll(utfbom.SkipOnly(bytes.NewReader(bodyWithBom))) // skip BOM
//...
gocsv.UnmarshalBytes(dataWithoutBom, &SomeData)
`

**Comment by marcsantiago** [comment]
That's another great solution. It may be worth while incorporating that
package within gocsv to handle BOM internally.
