### ISSUE TITLE
Embeded struct, if not an array| slice, won't get ignored with - tag

### ISSUE THREAD

**Issue by ninaRali** [gocarina/gocsv#168]
In case there is a struct within the initial struct with a `csv: "-"` and it is not an array, it will be included in the resulting csv. Maybe below example will make it more clear:

If you look at `gocsv.MarshalString` with an array of `&Invoice` you'll see ShippingAddress fileds flattened in the CSV file while Gateway is correctly ignored. (Note: I've removed ` for skipping styling from around tags)

`
type ShippingAddress struct {
	InvoiceID int64
	Address   string json:"address"
	City      string json:"city"
	State     string json:"state"
	Zip       string json:"zip"
	Country   string json:"country"
	Fax       string json:"fax"
}

type Gateway struct {
	InvoiceID       int64
	Configured      bool   json:"configured"
	AdditionalField string json:"additional_field"
	GatewayName     string json:"gateway_name"
}

type Invoice struct {
	InvoiceID    int64           json:"invoice_id"
	ShippingAddr ShippingAddress json:"shipping_address" csv:"-"
	GatewayArr   []Gateway       json:"shipping_address" csv:"-"
}
`

**Comment by pietv** [comment]
This issue is still appears to be present. @gocarina Are you confirming it and/or accepting a PR?

**Comment by jpincas** [comment]
Agreed, just started using the library and observed this behaviour, which is unexpected IMHO.
