### ISSUE TITLE
No double quotes are escaped

### ISSUE THREAD

**Issue by fananchong** [gocarina/gocsv#177]
like   `this is "xxxx".` , to csv file, must be `"this is ""xxxx""."`

Please refer to [https://golang.org/pkg/encoding/csv/](https://golang.org/pkg/encoding/csv/)

**Comment by mrzahrada** [comment]
@fananchong I am not sure if you have issue with `"` characters in values. If yes, then this helps:
```
gocsv.SetCSVReader(func(in io.Reader) gocsv.CSVReader {
	return gocsv.LazyCSVReader(in)
})
```

**Comment by fananchong** [comment]
thanks
