### ISSUE TITLE
parse error on line 1, column 14: bare " in non-quoted-field

### ISSUE THREAD

**Issue by chaunsin** [gocarina/gocsv#186]
parse error on line 1, column 14: bare " in non-quoted-field
what should i do?

**Comment by mrzahrada** [comment]
I've got same issue

**Comment by mrzahrada** [comment]
@chaunsin calling 
```
gocsv.SetCSVReader(func(in io.Reader) gocsv.CSVReader {
	return gocsv.LazyCSVReader(in)
})
```

solved the issue

**Comment by chaunsin** [comment]
> @chaunsin calling
> 
> ```
> gocsv.SetCSVReader(func(in io.Reader) gocsv.CSVReader {
> 	return gocsv.LazyCSVReader(in)
> })
> ```
> 
> solved the issue

thank you! I've solved the problem ,My problem is due to UTF-8 BOM coding.
```
import(
        "encoding/csv"

        "github.com/gocarina/gocsv"
        "golang.org/x/text/encoding/unicode"
	"golang.org/x/text/transform"
)

in := csv.NewReader(transform.NewReader(bytes.NewReader(raw), unicode.UTF8BOM.NewDecoder()))
if err := gocsv.UnmarshalCSV(in, &out); err != nil {
	return err
}
```
