### ISSUE TITLE
The error message is incorrect while struct is empty

### ISSUE THREAD

**Issue by Jannchie** [gocarina/gocsv#187]
``` go
type Word struct {
// it is empty
}
wordsFile, _ := os.OpenFile("word.csv", os.O_RDWR|os.O_CREATE, os.ModePerm)
if err := gocsv.UnmarshalFile(wordsFile, &words); err != nil {
	panic(err) 
}
```

Exceptions will occur in this code.

```
panic: empty csv file given
```

This exception is misleading because my CSV is not empty and the reason for the exception is that the struct does not have any fields.

**Comment by ABGEO** [comment]
I think this issue is outdated and we can close it.

Currently, if the structure is empty, `gocsv` returns this error: https://github.com/gocarina/gocsv/blob/02d7211d929db635a5fe7d0881923c72fddd85de/decode.go#L37
