### ISSUE TITLE
Custom Separator

### ISSUE THREAD

**Issue by AxelRHD** [gocarina/gocsv#257]
A possibility to change the separator - e. g. to tab - would be great.

**Comment by shigetaichi** [comment]
@AxelRHD  I have created a new package that allows the TagSeparator to be changed, and I have used gocsv as a reference for most of the csv generation process. (Thanks to all gocsv contributors.) I hope the ideas are helpful to you.
https://github.com/shigetaichi/xsv

**Comment by AxelRHD** [comment]
Thank you for the reply and the effort. I will give it a try after my vacation.
