### ISSUE TITLE
Columns with a blank header fail to unmarshal

### ISSUE THREAD

**Issue by User4574** [gocarina/gocsv#28]
See test case here: https://github.com/User4574/gocsvexample

**Comment by pikanezi** [comment]
Should we really handle blank headers? Would it be really useful?

**Comment by User4574** [comment]
I can only speak for myself, but this is blocking a project I am working on. The blank header is the first column, so rather than `UnmarshalFile` I'm planning to read in the file, append it to the name I want to use, and then `UnmarshalString` instead.

Speaking from the [csv RfC](https://tools.ietf.org/html/rfc4180) blank headers should be allowed.

**Comment by pikanezi** [comment]
Normally, blank headers are handle now, your test passed, could you try again in your project please?

**Comment by User4574** [comment]
This is working perfectly now, thanks!

**Comment by pikanezi** [comment]
You're welcome :)
