### ISSUE TITLE
optional header

### ISSUE THREAD

**Issue by porjo** [gocarina/gocsv#3]
It would be good to make the writing of the field header line optional

**Comment by Ganners** [comment]
I agree, it would be useful if it could have optional headers, it could be modified to use the column positions instead.

**Comment by leeychee** [comment]
+1

**Comment by challiwill** [comment]
+1

**Comment by challiwill** [comment]
My PR allows one to write your csv to the output (ie `Marshal`) without writing the headers. I think this is what @porjo was suggesting.

I'm not sure if this handles what @Ganners needs were.
