### ISSUE TITLE
Delimiters other than than comma

### ISSUE THREAD

**Issue by kathykeating** [gocarina/gocsv#35]
Pipe-delimited files are extremely common, there doesn't appear to be a way to overwrite the delimiter and that would be a necessary feature to be able to use this package.

**Comment by cowai** [comment]
@kathykeating How did you solve this?

**Comment by cowai** [comment]
nevermind.
```go
reader.Comma = ';'

**Comment by AndreasHerold** [comment]
Hey. I don't get it... where do I have to write the line
`reader.Comma = ';'` 
??
Maybe a extended documentation would be nice.
