### ISSUE TITLE
Parse error never returns from gocsv.UnmarshalToChan

### ISSUE THREAD

**Issue by notzippy** [gocarina/gocsv#37]
Hi

Noticed this when my CSV file had some bad data in it. If `decode.readEach` returns an error (https://github.com/gocarina/gocsv/blob/master/decode.go#L193) it does not close the channel and the program hangs .  maybe you could just add a `defer outValue.Close()` after it is initialized to avoid this ?

**Comment by pikanezi** [comment]
Hi,

I made a change, the channel will be close when an error occurs. Feel free to close this if it works for you.

**Comment by notzippy** [comment]
Looks good - thanks
