### ISSUE TITLE
How to deal with Embedded struct ?

### ISSUE THREAD

**Issue by ygbillet** [gocarina/gocsv#4]
I want to Unmarshal CSV into a struct with an embedded struct.
Does not seem to work. 

    type Identity struct {
    	Supplier string `csv:"supplier"`
    	Id       string `csv:"id"`
    }
    type Product struct {
    	Identity
    	Price int `csv:"price"`
    }

Do you have any pointer to make it work ?

**Comment by pikanezi** [comment]
In this case, what kind of output would you expect? I imagine something like that:

```
supplier,id,Price
Sup,1234,12.50
```

**Comment by andrei-m** [comment]
+1 it would be useful to have this.
