### ISSUE TITLE
Proposal: Unmarshalling into pointer fields

### ISSUE THREAD

**Issue by moorereason** [gocarina/gocsv#41]
Currently, unmarshalling pointers to built-in types (like `*string`) doesn't work without implementing an interface.  This feature should support that natively.

## Rationale

Unmarshalling into pointer types allows us to make fields optional; otherwise, unmarshalling a partial record would set zero values for the missing fields in the resulting struct, and you wouldn't know if it was because the field was blank or absent.

I have a scenario where I need to accept a subset of supported fields and update a database.  I want to make most of the fields optional and only update database fields that are present in a given CSV file.

## Example Struct

Given the following `User` struct:
```go
type User struct {
    ID         int     `csv:"user_id"`
    Username   string  `csv:"username"`
    LocationID int     `csv:"location_id"`
    ExternalID *int    `csv:"external_id"` // optional
    Nickname   *string `csv:"nickname"`    // optional
}
```

## Example Input

```plain
user_id,username,external_id
1,userA,1000
2,,
```

Notice that the `location_id` and `nickname` fields are absent.

## Example Result

Any fields **present** in the CSV with empty values would receive a Go zero-value in the resulting struct.  Any **missing non-pointer fields** would also receive a Go zero-value.  Any **missing pointer fields** would retain a nil value.

```golang
[]User{
    {
        ID: 1,
        Username: "userA",
        LocationID: 0,
        ExternalID: (*int)1000,
        Nickname: nil,
    },
    {
        ID: 2,
        Username: "",
        LocationID: 0,
        ExternalID: (*int)0,
        Nickname: nil,
    },
}
```

**Comment by jpmeijers** [comment]
I was trying to unmarshal an empty field into a `*float64`. The value that I end up with is not nil as expected, but a valid value of `0`.
