### ISSUE TITLE
sql.Nullstring

### ISSUE THREAD

**Issue by fils** [gocarina/gocsv#43]
If I am using a sql.NullString in my struct, is there a way to define a custom handler then to allow this to be sent through as a string?  I am trying this code in https://github.com/OpenCoreData/ocdServices/blob/master/janus/ageModel.go and it works but does serialize the sql.NullStings.   

Thanks!  nice package

**Comment by pikanezi** [comment]
Hello,

As sql.NullString is not a struct you own, your only way would be to create a subclass of it and create the methods ```MarshalCSV() (string, error)``` and ```UnmarshalCSV(string) error```.

Something like this:

```go
type SQLNullString struct {
         sql.NullString
}

func (s SQLNullString) MarshalCSV() (string, error) {
         return s.String, nil
}
```

(I did not test the code)

**Comment by fils** [comment]
Thanks!

I tested it and seems to be working just fine.  Appreciate it.

**Comment by pikanezi** [comment]
My pleasure :)
