### ISSUE TITLE
Accept custom csv reader for Unmarshal function?

### ISSUE THREAD

**Issue by challiwill** [gocarina/gocsv#46]
How would you feel about a PR that would change [this function](https://github.com/gocarina/gocsv/blob/master/csv.go#L148) to take in a csv Reader interface instead of the type itself? 

This interface would be defined in the package and look something like: 
``` go
type CSVReader interface {
    Read() ([]string, error)
    ReadAll() ([][]string, error) // Maybe without this function even because I don't think it's used
}
```

**Comment by pikanezi** [comment]
I don't feel good when making a breaking change. What would be the benefits of changing the main function of the package? What are your needs?

**Comment by challiwill** [comment]
Would this be a breaking change? I would think all the changes would just be generalizing what exists already:
```
type CSVReader interface {
    Read() ([]string, error)
    ReadAll() ([][]string, error) // Maybe without this function even because I don't think it's used
}

type csvDecoder struct {
	CSVReader
}

func UnmarshalCSV(in CSVReader, out interface{}) error {
	return readTo(csvDecoder{in}, out)
}
```

The problem I'm trying to solve is I have `.csv`s that are malformed in many ways so I want a `ReadFilter` that skips over rows that are unnecessary. These rows are malformed in enough ways that they break when sent through gocsv because of irregular lengths, or trailing commas. Currently my ideas are:
1. Read it all in with the `csv.Reader` and remove unwanted rows, then convert back to some kind of `io.Reader` and send into `gocsv` (or at that point just unmarshal it myself into a struct)
1. Update `gocsv` to allow custom csv readers that allow one to filter out unnecessary lines
1. Update `gocsv` to not break on variable length rows (seems hard though given the whole point is to decode the `.csv` into a standard struct.

**Comment by JonathanPicques** [comment]
Thanks for the PR.
