### ISSUE TITLE
How to deal with pointers?

### ISSUE THREAD

**Issue by DBrown2207** [gocarina/gocsv#5]
I have structures with the format:

    type Customer struct {
        Email      *string    `json:"email,omitempty" csv:"email"`
        FirstName  *string    `json:"firstName,omitempty" csv:"firstName"`
        LastName   *string    `json:"lastName,omitempty" csv:"lastName"`
    }

The values are pointers so that they can be nil. Works fine with go's json marshaller but returns the error:
>No known conversion from *string to string, *string does not implements TypeMarshaller nor Stringer

**Comment by JonathanPicques** [comment]
Fixed by PR #27
