### ISSUE TITLE
MarshalChan panics on a closed channel with no values

### ISSUE THREAD

**Issue by ebonetti** [gocarina/gocsv#53]
Calling MarshalChan on a closed channel (with no values) causes panic.
The error culprit is the zero value read from the channel - "firstValue := <-c" - at:
https://github.com/gocarina/gocsv/blob/master/encode.go#L20

To reproduce the error: https://play.golang.org/p/1Hvmg1V9J3

Keep up the good work,
Enrico

**Comment by pikanezi** [comment]
Hello,

I do not have the panics occuring (even using the provided example), but I have made a check, thank you!

Vincent
