### ISSUE TITLE
Consider http://labix.org/gopkg.in usage

### ISSUE THREAD

**Issue by dynbit** [gocarina/gocsv#54]
Hello!

We would like you to add tag (e.g. `v1.0`) for current master head, so we would be to use `gopkg.in` and lock our code on certain version/commit of `gocsv`.

Thanks in advance!

**Comment by pikanezi** [comment]
Alright, I'll look into it.

**Comment by pikanezi** [comment]
Hello, I created a branch v1, so now you can use this package like gopkg.in/gocarina/gocsv.v1
