### ISSUE TITLE
Working with map

### ISSUE THREAD

**Issue by sundarv85** [gocarina/gocsv#55]
Would it be possible to create a map of two fields. For e.g. 

```
client_id,client_name
4,Jose
2,Daniel
5,Vincent
```

I'm looking to create a `map[client_id]client_name`

Of course, after writing it into a struct, I could create a map. But it would be easier and simpler if gocsv could also do this automatically. Any thoughts?

**Comment by pikanezi** [comment]
It's really specific but does not harm the project in any way. I will see what I can do about that, thanks for the suggestion :)
