### ISSUE TITLE
How about custom delimiter instead of commas

### ISSUE THREAD

**Issue by keymastervn** [gocarina/gocsv#6]
What I may say is somehow trivial for csv format.
Due to our tab-delimiter input from my customer , I am currently modifying `gocsv` to support tab delimiter instead of comma delimiter. 

So, why not support custom delimiter like golang basic library [encoding/csv](https://golang.org/pkg/encoding/csv/)
```
type Reader struct {
        Comma            rune // field delimiter (set to ',' by NewReader)
       ...
}
```

**Comment by jamesgarfield** [comment]
@keymastervn Isn't this already supported via the customizable csv Reader? https://github.com/gocarina/gocsv#customizable-csv-reader--writer

**Comment by JonathanPicques** [comment]
Like @jamesgarfield said, it's already possible

**Comment by alexliesenfeld** [comment]
But doesn't it set the comma globally, i.e., for the entire application? It should be possible to set this for one reader, not all files are equal ;-)
