### ISSUE TITLE
Race condition in UnmarshalToCallback()

### ISSUE THREAD

**Issue by aparnaclypd** [gocarina/gocsv#62]
Hi,

Facing race condition when I tried to use UnmarshalToCallback in my code. Running 

> `go test -v -race` 

detected 'race condition' when it tried to access same code, post spawning of goroutines. 

Refer attached log for more details.
[RaceCondition.txt](https://github.com/gocarina/gocsv/files/909712/RaceCondition.txt)

**Comment by pikanezi** [comment]
Hello,

Do you have a basic code sample or data which produces the above error?
It could help me greatly to track this error.

Thank you.

**Comment by aparnaclypd** [comment]
Hello,

I do not have sample data as such with me. However, I ran `go test -v -race` on the cloned gocsv repo, that should also reproduce the issue for you.

Thank you.

**Comment by pikanezi** [comment]
Yes, I see, thank you :) I will fix this ASAP.

**Comment by aparnaclypd** [comment]
That would be great. Thank you. :)

**Comment by pikanezi** [comment]
It has been fixed (at least that's what the race condition tester tells).

Thank you for your report :) have a nice day.

**Comment by aparnaclypd** [comment]
Thanks a lot for your quick response! :)
