### ISSUE TITLE
UTF8 Byte Order Marker causes me to lose first field

### ISSUE THREAD

**Issue by ianmcmahon** [gocarina/gocsv#63]
I had a bizarre issue where I was always losing the first field in my unmarshaled CSV files, I dug in and figured out that it was because the first header string, when printed as a byte array, had the UTF-8 BOM as part of it.  I was able to work around by tagging my first fields like this:

	Code         string `csv:"\xEF\xBB\xBFCODE,CODE"`

**Comment by pikanezi** [comment]
Hello, I will look into it tonight or tomorrow, thank you for your report and I'm glad you found a workaround.

**Comment by pikanezi** [comment]
After some research, especially seing this [issue](https://github.com/golang/go/issues/9588), I'm not sure that I should check if there is actually a BOM before doing anything.
Can't you convert your files before unmarshaling?

**Comment by ianmcmahon** [comment]
Yeah, that definitely makes sense, I'm just not sure the best way to go about it.  I'd like to be able to do it streamwise (ie with a translating buffer or something), because my data files are on the order of 200MB.

**Comment by ianmcmahon** [comment]
found something:
https://github.com/spkg/bom

**Comment by pikanezi** [comment]
You could use this library personally to customize the reader gocsv will use and, that way, remove the BOM.

Something like that

```

import "github.com/spkg/bom"

---
---
---

gocsv.SetCSVReader(func (in io.Reader) *csv.Reader {
		return csv.NewReader(bom.NewReader(in))
})
```

I tried and seems to work.

**Comment by trentontrees** [comment]
Just ran into this as well.  It would be wonderful to have an indication that BOM was detected.
