### ISSUE TITLE
Trim trailing spaces?

### ISSUE THREAD

**Issue by ianmcmahon** [gocarina/gocsv#64]
I'm dealing with data that is fixed width csv, and I'd like to have a simple method for trimming trailing spaces.  I know that the leading space trimming is handled by encoding/csv, but I was looking for a way to do it by providing a custom CSVReader that wraps LazyCSVReader, or something along those lines.  I can't seem to get my head around how to do that, is it possible to provide implementations of the Decoder or CSVReader interfaces?

**Comment by pikanezi** [comment]
To solve your problem, I had no other choice than adding a new API: UnmarshalDecoder, UnmarshalDecoderToChan and UnmarshalDecoderToCallback.

A test has been added so you can have an example of how to use them (the example how to trim spaces might have been handled poorly, feel free to modify it at your convenience).

**Comment by hassansin** [comment]
@pikanezi how do we implement a trim decoder outside the package since `Decoder` interface has no exported methods?
