### ISSUE TITLE
Content containing commas

### ISSUE THREAD

**Issue by jetbasrawi** [gocarina/gocsv#78]
Hi, this is not really an issue with your software but in using it with dumb data source.

There are four colums in the CSV, one of the columns contains ordinary text data that may also contain commas. Horrible. There is a phone number, a date, sent/received,Subject,Content

An example row is like this
,+447755505585,08-22-2013 08:43:12,Send,,**Some text, which may contain commas**

Does your library provide any way that I can handle this case?

Many thanks

**Comment by pikanezi** [comment]
Hi,
Can we still call this valid csv? I'm not sure the library can help you with this, the subject and content both can contains comma?

**Comment by jetbasrawi** [comment]
Don't worry, I am just going to read the file line by line and manually handle this case. Thank you.
