### ISSUE TITLE
[feature request]Handle unmarshaling without CSV headers

### ISSUE THREAD

**Issue by nathanielobrown** [gocarina/gocsv#85]
I need to unmarshal some CSVs without headers. As far as I understand, there is no way to do this with this library currently.

It seems we need a new function like `UnmarshalWithoutHeaders` just like the `MarshalWithoutHeaders` that was created in the issue #3. I would think that the order of fields in the struct you are unmarshalling to could be used to map columns, or we could use an index struct tag similar to this libarary: https://github.com/yunabe/easycsv.

I'm a Go noob so please tell me if I have things very wrong. If this feature does make sense, I'd be happy to try taking a stab at this, but I think I might need some guidance!

**Comment by DDCrow** [comment]
I already create a PR in #86 for this feature

**Comment by pikanezi** [comment]
If #86 meets your need, feel free to close this issue

**Comment by nathanielobrown** [comment]
That works, thank you @DDCrow!
