### ISSUE TITLE
make toBool() ignore uppercase when strings are input

### ISSUE THREAD

**Issue by moosecanswim** [gocarina/gocsv#92]
I dont see a reason why "Yes" =/= "yes" when converting a csv string to bool.

https://github.com/gocarina/gocsv/blob/a7422e75c1caf4c04c1b413ad1cd857d3eebb85c/types.go#L93

**Comment by JonathanPicques** [comment]
Why not, feel free to open a pull request

**Comment by cclulu** [comment]
If no one is working on it, I would like to work on this, if that is okay?

**Comment by cclulu** [comment]
I made a [pull request](https://github.com/gocarina/gocsv/pull/98) for this. Let me know if I did anything wrong.

**Comment by JonathanPicques** [comment]
Merged, thanks :)
